### PR TITLE
fixed AudioFile compatibility

### PR DESCRIPTION
**Pull request by SentulAsia**
self.becomeFirstResponder() is done in viewDidLoad and remoteControlReceivedWithEvent as well... how do you want to incorporate both of this into ColiseuPlayer?

### CODE REVIEW

**Comment by ricardopereira** [comment]
Well, about `becomeFirstResponder` and `remoteControlReceivedWithEvent`, I haven't thought about it. Do you have any suggestion?

**Comment by ricardopereira** [comment]
@SentulAsia ^

**Comment by ricardopereira** [comment]
Please check that whitespace and then I merge it.

**Comment by SentulAsia** [comment]
Ok found the culprit...
screen_shot_2015-10-22_at_2 09 41_am

**Comment by SentulAsia** [comment]
ok @ricardopereira after enabling the whitespace from xcode, all the whitespace has been trimmed... u can merge it now...

**Comment by ricardopereira** [comment]
Thank you.

**Pull request merged**
