### PR TITLE
swift 5.0 compatibility

### PR DESCRIPTION
**Pull request by SentulAsia**
Upgraded the swift files to swift 5.0, I leave it to you to update the project.pbxproj

### CODE REVIEW

**Comment by ricardopereira** [comment]
@SentulAsia I think yes, I recall having a similar issue. I'm suspicious it could be something related to not handling well the `AVAudioSession`.

**Comment by SentulAsia** [comment]
@ricardopereira ok thanks, maybe I will try to debug it if I have time...

**Comment by SentulAsia** [comment]
@ricardopereira I have several additional delegate and feature that I need, can I add it to this project?
Should I create an issue first and you check if it can be added in this project?

**Comment by SentulAsia** [comment]
@ricardopereira any new on this?

**Comment by ricardopereira** [comment]
Let's do this. Thanks

**Pull request merged**
