### PR TITLE
done unit test for all public method

### PR DESCRIPTION
**Pull request by SentulAsia**
@ricardopereira the unit test should now cover all possible cases.
Please do indicate if I miss anything or there is something else to be tested.
I would love to learn on how to write performance testing, if you have a source that I can learn from, it would be helpful.

### CODE REVIEW

**Comment by SentulAsia** [comment]
@ricardopereira I wonder if this helps? https://discuss.bitrise.io/t/how-to-create-a-virtual-audio-output-device-on-mac-os-stacks/1119/7

**Comment by ricardopereira** [comment]
@SentulAsia Well, I added that step into the Bitrise workflow and the test suite fails. Does it work on your machine? All tests pass?

**Comment by SentulAsia** [comment]
@ricardopereira the unit test at bitrise when it tries to check if audio is playing... I assume bitrise don’t have an audio output hence audio can’t be played...
In local machine it passes because I have an audio output... in the link above, i’ve posted a possible solution for bitrise...

**Comment by ricardopereira** [comment]
@SentulAsia Yes, I noticed. I applied that solution but it fails anyway 😕

**Comment by ricardopereira** [comment]
Maybe we should abstract the `AVAudioPlayer` in a way where we could mock it in the test suite.

**Comment by SentulAsia** [comment]
Ok’ i’m on it... will submit a separate PR for that...

**Comment by ricardopereira** [comment]
Thanks a lot

**Pull request merged**
